randovania/mercury-engine-data-structures

mercury_engine_data_structures/formats/__init__.py
mercury_engine_data_structures/formats/bldef.py

Adds support to open BLDEF (Light Definition/CLightManager) files. 
These have a bit of a weird format -- they have similar structure to `standard_format` files but there are two types of CLightManager. One is an outer one that contains version string, the Root element, and a field `pLightManager: CLightManager`. `standard_format.create()` doesn't like this since there isn't a `pLightManager` data type, so I copied and modified the function so it won't try to match `pLightManager` to a type. 
I'm not sure if the other params in `standard_format.create()` would let us get around that, so review appreciated :]

Added BLDEF support

---

mercury_engine_data_structures/file_tree_editor.py
mercury_engine_data_structures/formats/__init__.py
mercury_engine_data_structures/formats/bmslgroup.py
mercury_engine_data_structures/formats/bmslink.py
mercury_engine_data_structures/formats/bmtre.py

Bmtre's are behavior trees; parsing is implemented and includes a `Bmtre.print_tree()` function that pretty-prints using the control nodes in behaviortree namespace (CRepeat, CIf, CSequence, CSelector, CParallel). 
Bmslgroup's are a standard format that references a bmslink file. 
Bmslink's are a non-standard format that connects actors with the navmesh. This is largely used for entities that travel along walls, such as Emmys, Autclasts, Infesters and Saboturu. It can parse all files currently, but I'm not sure what most of the parameters are; I would appreciate review to see if anyone can figure out what is going on.

Support for Bmtre, Bmslink, Bmslgroup

---

.github/workflows/python.yml

build uses pip to install dependencies, and pip raises a deprecation warning (see https://github.com/pypa/pip/issues/12243).

Remove PYTHONWARNINGS=error during build

---

src/mercury_engine_data_structures/formats/pkg.py

No idea how to provide tests due to the fact that the padding within the pkg looks totally random. (some pkg's even have odd number of bytes)

Apply alignment after header in pkg

---

src/mercury_engine_data_structures/formats/bmsbk.py

According to DCR `unk4` is the respawn time for the blocks, where 0.0 means it nevers respawn and if greater than 0.0 it's the time in seconds.
@dyceron Are there other fields we could rename? There was a "always visible" thing but I don't know to which field it was related.

Rename bmsbk field

---

src/mercury_engine_data_structures/formats/bmsld.py
src/mercury_engine_data_structures/samus_returns_types.json
tests/formats/test_bmsld.py

Rotating a shield around y-axis:
0: ![0](https://github.com/randovania/mercury-engine-data-structures/assets/117127188/c93e6d37-e0e7-4b31-afd7-edd0078848df)
90 (I use this for now as a "cheat" to at least have it wrongly visible on both sides):
180: ![180](https://github.com/randovania/mercury-engine-data-structures/assets/117127188/a1748280-1e0a-468d-9c5e-48c13e4a0f15)

Rename unknown, add all_actors method

---

src/mercury_engine_data_structures/formats/bmsld.py

I hope that we finally figured it out: The "magic" sorting of the actors is by their crc32 value, so MEDS should take care of that and provide the helper functions.
(btw: I'm open for a more efficient way to keep the list sorted)

Add actors sorted by CRC in Bmsld entity groups

---

src/mercury_engine_data_structures/file_tree_editor.py

In `save_modifications` MEDS is creating a `modified_pkgs` set but it only adds a pkg to the set, if you have modified ressources or have added ressources to it but not if you only have used the `ensure_present` method. The last method only adds it to `_ensured_asset_ids`, so it is reasonable to iterate through it and add these pkgs.
This is relevant for MSR as it has a `AREA_NAME.pkg` but also a `AREA_NAME_discardables.pkg`. In the first one we ensure all the models, animations etc., while the second contains the scenario BRFLD, lua files and BMSAD.
Let's hope that nothing breaks for Dread (but we are using RomFS export anyways now?)

Write pkgs with only ensured assets

---

src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bmsmsd.py
tests/formats/test_bmsmsd.py

Oh look, a MEDS change for MSR.
Adds support for the minimap files.
`unk1` and `unk2` are always 800.0 in the files I looked at. Guess we can ignore it.
No clue about `unk3`, `unk4` `unk5`. Maybe some sort of type. Guess DCR finds it out when playing around with it 😛
I thought that `x_tiles` and `y_tiles` in the header part defines the dimension in tiles, which was matching really good (and still kinda does)...until I found a save station which uses a value one greater than defined. But it's still my best guess.

Add support for BMSMSD

---

src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bmsmd.py
tests/formats/test_bmsmd.py

I'm not sure what most of these unknowns are and I don't know if all the data types in `sub_scenarios` is 100% correct.

MSR - Support .bmsmd

---

src/mercury_engine_data_structures/formats/pkg.py

That's a fun one: The file header contains of `asset_id`, `start_offset` and `end_offset` for each file.
But it's an prefixed array and the 4 bytes for the length are missing when skipping over it via `stream_seek`.
When the pkg doesn't need alignment without the missing 4 bytes, the header will overwrite the first 4 bytes of an actual file, which you can see in SR here: https://user-images.githubusercontent.com/117127188/284011718-8a40aa69-8561-452e-b4fe-fdc09d9dd6c1.png
I don't know why I haven't seen it, when I added the alignment for SR because it was already visible there.

Skip over correct length for the header in pkg files

---

src/mercury_engine_data_structures/formats/pkg.py

Samus Returns requires a different pkg alignment than Dread. This allows the files to be built properly and allow the rando to function on console (and fix Citra issues).

Adjust pkg alignment for SR

---

.github/workflows/python.yml

Could be that because the runner only runs stuff on branches `main`, that it never gets to run the temporary merge queue branches.

Try to tell self-host CI to use merge queue

---

src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/blsnd.py
tests/formats/test_blsnd.py

I have no idea what these values do or what the file really does. I was just bored. 😛

MSR - Add .blsnd support

---

src/mercury_engine_data_structures/formats/collision.py

- Discovered that the AABOX2D format is not (unk, min, max) but is (center, unk, size)
- center is the "center" of the rect as an offset from the actor vPos
- size is the (w, h) of the box
- unk seems to be 0 in the examples i'm working with
- to render the box ( (cx, cy), u, (w, h) ), the coordinates are:
- left: vPos.x + cx - w/2
- right: vPos.x + cx + w/2
- top: vPos.y + cy - h/2
- bottom: vPos.y + cy + h/2
screenshots for evidence:
first artaria blob:
cloak doors in corpius access (large box is  the sensor collider):
screw attack room  spinner (boxes on the sides are the colliders to turn it, I assume  only the right is activated):
hidden door in cataris below first EMMI entrance:
Burenia hub to dairon, underwater blob section:

Fixed AABOX2D collision

---

src/mercury_engine_data_structures/formats/collision.py

- im stupid, turns out it's a vec3 for the AABOX's vPos's offset and it also applies to POLYCOLLECTION2D and presumably CIRCLE as well...

polycollection2d fix

---

src/mercury_engine_data_structures/formats/pkg.py
tests/formats/test_pkg.py

This is the code which can parse and rebuild all pkg files except 11 files. The only problem is the end of the file.
Always end with 0 padding at the end of the file except for `MSCU` `MTXT` `CUT ` which adds padding to align to 4 bytes.
- removing `MSCU` from special case => more files gonna fail
-  removing `MTXT` from special case => more files gonna fail
- adding `MSAT` to the special case => more files gonna fail
The `wrong_build_sr` case in the test is written in a weird way on purpose. It proofes that, of course, the length field is wrong but besides that it's only the ending which is wrong.
Don't know if it should merged 🤷‍♂️

Build vanilla PKGs in SR

---

src/mercury_engine_data_structures/construct_extensions/json.py

this was causing an issue dumping navmeshes, since emmy traversals use integer keys.

fixed bug in --dump-to flag

---

src/mercury_engine_data_structures/formats/bmscc.py

`construct.core.ConstError: Error in path (parsing) -> _version -> minor`
`parsing expected 14 but parsed 13`
🙃

MSR - Fix wrong minor version for bmscc

---

README.md
src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bnvib.py
tests/formats/test_bnvib.py

standard NX library format, already documented online https://switchbrew.org/wiki/BNVIB#Normal_Vibration

Added bnvib

---

README.md
src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bptdat.py
tests/formats/test_bapd.py
tests/formats/test_bnvib.py
tests/formats/test_bpsi.py
tests/formats/test_bptdat.py

- standard format
- fixed test names for some files (copy-paste moment)

BPTDAT and BPTDEF

---

src/mercury_engine_data_structures/formats/bmsad.py
tests/formats/test_bmsad.py

bmsad.py L270-L282 for non-formatting changes. 
- IfThenElse checks for a too-small component field length and replaces the correct value
- Throws an error on parsing if the size of a DreadComponent.fields is 0x1C and DreadComponent.fields.fields is not length 1 and an eDefaultCollisionMaterial
- applied / formatting to bmsad.py instead of = formatting in applicable locations
- updated tests to check parse-build-parse on this file

Repair encoding error in actors/props/pf_mushr_fr/charclasses/pf_mushr_fr.bmsad

---

README.md

Includes some notes to help parse what each type is for, as well as a little info on them that I have knowledge of.

Update README with more info regarding mercury formats

---

README.md
src/mercury_engine_data_structures/common_types.py
src/mercury_engine_data_structures/formats/bmssd.py
tests/formats/test_bmssd.py

- now uses an adapter to place blocks, objects and lights in hidden keys and puts the objects in the scene group data
- rebuilds all but 4 msr files with missing crc values
- added function to get a block or light by name
- added function to get a scene group
- added function to find scene groups an item belongs to
- added function to remove an item from a scene group
- added function to add an item
- added function to remove an item
- beeg test function
screenshot of sample `--dump-to` output. functions should be able to do anything user would want to without requiring manipulating `raw` input.

BMSSD refactor

---

src/mercury_engine_data_structures/formats/bmscc.py
tests/formats/test_collision.py

- Cleans up formatting
- Adds functions to modify points and access other collision data

BMSCC Refactor

---

src/mercury_engine_data_structures/formats/bmssd.py
tests/formats/test_bmssd.py

Tried to use the new API in OSRR and failed :(
1. Not every `ItemType` is in every `sg_val` which leads to a KeyError if we only use `sg_val[item_type]` without a check before.
2. `remove_item` needs to respect if we want to remove from a `dict` or a `list` where `SCENE_BLOCK` and `LIGHTS` using a dict but `OBJECT` a list. I added a test to also remove from a `dict` (which is what we do in OSRR).

Fix BMSSD API

---

src/mercury_engine_data_structures/formats/bmsbk.py
tests/formats/test_bmsbk.py

BMSBK - Minor cleanup and add functions

---

src/mercury_engine_data_structures/adapters/flagsenum_adapter.py
src/mercury_engine_data_structures/common_types.py
src/mercury_engine_data_structures/formats/bmsmsd.py
tests/formats/test_bmsmsd.py

Adds new classes to change tiles and icons

Add classes to BMSMSD

---

src/mercury_engine_data_structures/formats/bmdefs.py
tests/formats/test_bmdefs.py

Adds new classes for accessing sound properties

Add classes and functions to BMDEFS

---

tools/extract_pkg.py

Due to changes made in #232, extracting pkgs broke with a `unhashable type: 'dict'` error. This now fixes that issue.
Credit to Thanatos

Fix extract_pkg not working

---

src/mercury_engine_data_structures/formats/bmsbk.py
tests/formats/test_bmsbk.py

Now has classes with properties to better handle modifying `block_groups`

Add classes to BMSBK

---

.gitignore
.vscode/settings.json

Adds a basic settings file, then gitignores the `.vscode` folder

Add VSCode folder to gitignore

---

src/mercury_engine_data_structures/sr_resource_names.json

As I never got any answer to the issue, here is the sledgehammer approach by just regex over the file and remove all empty versions array for pkg files.
This should be now again at 417 passed, 25 skipped as it was in v0.32.0 instead of 2 passed, 2 skipped since v0.33.0
Fixes #270

Fix pkg tests
