mercury_engine_data_structures/formats/__init__.py
mercury_engine_data_structures/formats/bmbls.py
mercury_engine_data_structures/formats/game_model_root.py
test/formats/test_bmbls.py

Add BMBLS format

---

mercury_engine_data_structures/formats/txt.py
test/formats/text_txt.py
tools/create_class_definitions.py

- converts flagsets to FlagsEnum rather than simple Enum
- adds TXT format support

couple things for patcher needs

---

mercury_engine_data_structures/formats/bmscc.py

- this format contains an unknown integer and a min and max CVector2's
- also fixes #26 by commenting out EOF check at the end until a real solution is found

Added AABOX2D to collision formats

---

src/mercury_engine_data_structures/formats/bcmdl.py
src/mercury_engine_data_structures/formats/bmsnav.py
tests/formats/test_bcmdl.py

Also remove one of bcmdl's tests as it's redundant and very slow.

Optimize BCMDL and BMSNAV

---

src/mercury_engine_data_structures/common_types.py
src/mercury_engine_data_structures/construct_extensions/__init__.py
src/mercury_engine_data_structures/construct_extensions/strings.py
src/mercury_engine_data_structures/formats/bmsas.py
src/mercury_engine_data_structures/formats/property_enum.py

Since this improves Hex/PascalStringRobust/CRCAdapter, it should also slightly speed up everything else.

Speedup BMSAS

---

src/mercury_engine_data_structures/common_types.py
src/mercury_engine_data_structures/formats/bmsad.py
tests/conftest.py
tests/formats/test_bmsad.py

Depends on #52.
Except for two specific BMSAD, parses all components of all the other files.

Progress in BMSAD for SR

---

tools/extract_pkg.py
tools/filter_file_names.py
tools/ghidra_export.py
tools/update_hashes_with_field_names.py

Paths moved to src...or I'm using it in a wrong way.

Tools were using old folder structure

---

src/mercury_engine_data_structures/common_types.py
src/mercury_engine_data_structures/construct_extensions/enum.py
src/mercury_engine_data_structures/construct_extensions/function_complex.py
src/mercury_engine_data_structures/construct_extensions/strings.py
src/mercury_engine_data_structures/formats/txt.py
src/mercury_engine_data_structures/object.py
src/mercury_engine_data_structures/pointer_set.py
tests/formats/test_bmmap.py

Starter: 3.2s
April Fools: 5.5s
Starter: 2.8s
April Fools: 5.0s

Even further optimizations

---

src/mercury_engine_data_structures/formats/bmscc.py
src/mercury_engine_data_structures/formats/bmsld.py
src/mercury_engine_data_structures/formats/collision.py

I changed stuff in MEDS and I have no idea what I'm doing :)
Main issue is that current MEDS parses the COLLECTION2D wrong. It's actually the same as in BMSCC that's why I moved the definitions to a new file.

Fixes for SR (BMSLD collision / logic shapes)

---

src/mercury_engine_data_structures/formats/bmsmsd.py

Yay another another MEDS change for MSR :) :)

MSR - Update TileType Enum and add Enum for Icon_Priority

---

src/mercury_engine_data_structures/formats/bmssd.py
tests/formats/test_bmssd.py

Not the full file, but stuff I've recently dealt with and changed.

Update bmssd sg fields for MSR

---

README.md
src/mercury_engine_data_structures/formats/blsnd.py
tests/formats/test_blsnd.py

- The table in the README contains all formats, including up-to-date info on whether each can be read/written for dread/SR or is missing
- made blsnd files readable by both games

Updated README with all formats

---

src/mercury_engine_data_structures/cli.py
src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bmsem.py
tests/formats/test_bmsem.py

Thanatos did the bulk of the work, I just cleaned it up slightly.

Adds BMSEM support

---

src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bmdefs.py
tests/formats/test_bmdefs.py

Adds support to bmdefs. I take no credit for 90% of this. Original branch from @ThanatosGit.
I didn't have push permissions for your fork, so I recreated the changes on my own fork.

MSR - Add support to bmdefs

---

README.md

Mark BMSEM and bsnav as being parsed in readme

---

src/mercury_engine_data_structures/common_types.py
src/mercury_engine_data_structures/construct_extensions/strings.py
src/mercury_engine_data_structures/formats/bmsld.py

Also adds StaticPaddedString, which is used by BMSLD's FunctionArgument

Allow `Char` to be compiled

---

src/mercury_engine_data_structures/formats/collision.py
tests/formats/test_collision.py

- added tests for bmscd and bmscc files in dread and samus returns
- added OBOX2D collision struct

Added tests for collision formats

---

README.md
src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/blut.py
tests/formats/test_blut.py

- really simple format, seems to be 1D lookup table.
- only used for Adam stations and controls the orb's animation

added BLUT (Binary LookUp Table?)

---

README.md
src/mercury_engine_data_structures/formats/gui_files.py
tests/formats/test_gui.py

Added BMSSH format

---

README.md
src/mercury_engine_data_structures/formats/__init__.py
src/mercury_engine_data_structures/formats/bpsi.py
tests/formats/test_bpsi.py

- implemented parse/build for bpsi on dread and SR

BPSI (pack set?)

---

src/mercury_engine_data_structures/formats/bcskla.py
src/mercury_engine_data_structures/formats/bmsas.py
tests/formats/test_bcmdl.py
tests/formats/test_bctex.py
tests/formats/test_bmbls.py
tests/formats/test_bmsad.py
tests/formats/test_bmscu.py
tests/formats/test_bmssd.py
tests/formats/test_bsmat.py
tests/formats/test_collision.py
tests/formats/test_gui.py
tests/formats/test_pkg.py
tests/formats/test_toc.py
tests/formats/test_txt.py

These are the most time consuming tests.
BCSKLA can be improved further, but it's proving tricky to compile it correctly.

Speedup parsing/building BCSKLA and BMSAS

---

src/mercury_engine_data_structures/formats/bmscc.py
src/mercury_engine_data_structures/formats/collision.py

The collision_formats are shared among multiple files, like bmscc/bmscd and bmsld, so I moved the class to the `collision.py` file. Now both formats can call this class directly.

Move `CollisionEntry` class to `collision.py`

---

src/mercury_engine_data_structures/formats/bmslink.py
src/mercury_engine_data_structures/formats/bmsnav.py
src/mercury_engine_data_structures/formats/collision.py

- researched and documented most parts of the mesh
- fixed some bools misclassified as bytes in bmslink
- fixed a (int1, int15) being read as a short in polycollection2d bst's

bmsnav fixes
